apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-2
resources:
  - helmrepo.yaml
  - helmrel.yaml
configMapGenerator:
  - name: bitkafka-values
    files:
      - values.yaml=my-values-external-listener.yaml
configurations:
  - kustomizeconfig.yaml