# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#configuration
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#configure-scan-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  SCAN_KUBERNETES_MANIFESTS: "true"

stages:
  - test

# Static Application Security Testing
sast:
  tags:
    - podman

# Secret Detection
secret_detection:
  tags:
    - podman
